### ISSUE TITLE
Create sample data file to back the draft API contract

### ISSUE THREAD

**Issue by lululeon** [colabco/cbld-api#3]
This ticket is to create / refine a sample data JSON file so that very early iterations of the api can serve sample data in adherence to the initial data contract (see ticket #2).

The data must provide sample data for the multiple users, projects and other entities that will be needed. The sample data file must envision/foresee the most likely:
- relationships between entities
- key fields needed for each entity (eg an id field)

The sample data file does not have to include metadata like created / updated timestamps, for simplicity.

### Acceptance Criteria
- [x] sample data file committed to repository
- [x] sufficient data values for exercising the draft API (ticket #2)

**Comment by blackxavier** [comment]
closes #3
